//: arrays/RaggedArray.java
package arrays; /* Added by Eclipse.py */

/* Exercise 16.03
 (4) Write a method that creates and initializes a twodimensional array of
double. The size of the array is determined by the arguments of the method, and the
initialization values are a range determined by beginning and ending values that are also
arguments of the method. Create a second method that will print the array generated by the
first method. In main( ) test the methods by creating and printing several different sizes of
arrays.
 */

import java.util.Arrays;
import java.util.Random;


public class Exercise1603 {
  static Random rand = new Random(47);
  static double[][] twoDimensional(int frist, int second, int beginning, int ending) {
    double[][] doubles = new double[frist][second];
    for (int i = 0; i < doubles.length; i ++) {
      for (int j = 0; j < doubles[i].length; j ++) {
        doubles[i][j] = beginning + rand.nextDouble() * (ending - beginning);
      }
    }
    return doubles;
  }

  static void printArray(double[][] doubles) {
    System.out.println(Arrays.deepToString(doubles));
  }

  public static void main(String[] args) {
    printArray(twoDimensional(3,4,0, 10));
  }
}
